import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import stylistic from "@stylistic/eslint-plugin";



const eslintConfig = defineConfig([
	{
		extends: nextVitals,
		rules: {
			"react/no-children-prop": "off",
		},
	},
	{
		extends: nextTs,
		rules: {
			"@typescript-eslint/no-empty-object-type": ["error", { allowInterfaces: "always" }],
			"@typescript-eslint/no-unused-vars": [
				"error",
				{
					args: "all",
					argsIgnorePattern: "^_",
					caughtErrors: "all",
					caughtErrorsIgnorePattern: "^_",
					destructuredArrayIgnorePattern: "^_",
					varsIgnorePattern: "^_",
					ignoreRestSiblings: false,
				},
			],
		},
	},
	{
		plugins: {
			"@stylistic": stylistic,
		},
		rules: {
			// https://eslint.style/packages/default#rules
			"@stylistic/array-bracket-newline": ["error", "consistent"],
			"@stylistic/array-bracket-spacing": ["error", "never"],
			"@stylistic/array-element-newline": ["off", { consistent: true, multiline: true }],
			"@stylistic/arrow-parens": ["error", "as-needed", { requireForBlockBody: true }],
			"@stylistic/arrow-spacing": ["error", { before: true, after: true }],
			"@stylistic/block-spacing": ["error", "always"],
			"@stylistic/brace-style": ["error", "1tbs", { allowSingleLine: true }],
			"@stylistic/comma-dangle": ["error", "always-multiline"],
			"@stylistic/comma-spacing": ["error", { before: false, after: true }],
			"@stylistic/comma-style": ["error", "last"],
			"@stylistic/computed-property-spacing": ["error", "never"],
			"@stylistic/curly-newline": ["error", { consistent: true }],
			"@stylistic/dot-location": ["error", "property"],
			"@stylistic/eol-last": ["error", "always"],
			"@stylistic/function-call-argument-newline": ["error", "consistent"],
			"@stylistic/function-call-spacing": ["error", "never"],
			"@stylistic/function-paren-newline": ["error", "multiline-arguments"],
			"@stylistic/generator-star-spacing": ["error", { before: false, after: true }],
			"@stylistic/implicit-arrow-linebreak": ["error", "beside"],
			"@stylistic/indent": ["error", "tab"],
			"@stylistic/indent-binary-ops": ["error", "tab"],
			"@stylistic/jsx-child-element-spacing": ["error"],
			"@stylistic/jsx-closing-bracket-location": ["error", "line-aligned"],
			"@stylistic/jsx-closing-tag-location": ["error", "line-aligned"],
			"@stylistic/jsx-curly-brace-presence": ["error", { props: "never", children: "never" }],
			"@stylistic/jsx-curly-newline": ["error", "consistent"],
			"@stylistic/jsx-curly-spacing": ["error", { when: "never" }],
			"@stylistic/jsx-equals-spacing": ["off", "never"],
			"@stylistic/jsx-first-prop-new-line": ["error", "multiline"],
			"@stylistic/jsx-function-call-newline": ["off", "multiline"],
			"@stylistic/jsx-indent-props": ["error", "tab"],
			"@stylistic/jsx-max-props-per-line": ["error", { when: "multiline", maximum: 1 }],
			"@stylistic/jsx-newline": ["off"],
			"@stylistic/jsx-one-expression-per-line": ["error", { allow: "single-line" }],
			"@stylistic/jsx-pascal-case": ["error"],
			"@stylistic/jsx-quotes": ["error", "prefer-double"],
			"@stylistic/jsx-self-closing-comp": ["error", { component: true, html: true }],
			"@stylistic/jsx-sort-props": ["off"],
			"@stylistic/jsx-tag-spacing": ["error", { closingSlash: "never", beforeSelfClosing: "never" }],
			"@stylistic/jsx-wrap-multilines": [
				"error",
				{
					declaration: "parens-new-line",
					assignment: "parens-new-line",
					return: "parens-new-line",
					arrow: "ignore",
					condition: "parens-new-line",
					logical: "parens-new-line",
					prop: "ignore",
					propertyValue: "ignore",
				},
			],
			"@stylistic/key-spacing": ["error", { beforeColon: false, afterColon: true }],
			"@stylistic/keyword-spacing": ["error", { before: true, after: true }],
			"@stylistic/line-comment-position": ["error", { position: "above" }],
			"@stylistic/linebreak-style": ["error", "unix"],
			"@stylistic/lines-around-comment": [
				"error",
				{
					beforeBlockComment: true,
					afterBlockComment: false,
					beforeLineComment: true,
					afterLineComment: false,
					allowBlockStart: true,
					allowBlockEnd: false,
					allowObjectStart: true,
					allowObjectEnd: false,
					allowArrayStart: true,
					allowArrayEnd: false,
					allowClassStart: true,
					allowClassEnd: false,
					allowEnumStart: true,
					allowEnumEnd: false,
					allowInterfaceStart: true,
					allowInterfaceEnd: false,
					allowModuleStart: true,
					allowModuleEnd: false,
					allowTypeStart: true,
					allowTypeEnd: false,
					afterHashbangComment: true,
				},
			],
			"@stylistic/lines-between-class-members": [
				"error",
				{
					enforce: [{
						blankLine: "always",
						prev: "method",
						next: "method",
					}],
				},
				{
					exceptAfterSingleLine: true,
					exceptAfterOverload: true,
				},
			],
			"@stylistic/max-len": [
				"error",
				{
					code: 140,
					tabWidth: 4,
					ignoreComments: true,
					ignoreTrailingComments: false,
					ignoreUrls: true,
					ignoreStrings: true,
					ignoreTemplateLiterals: true,
					ignoreRegExpLiterals: true,
				},
			],
			"@stylistic/max-statements-per-line": ["error", { max: 3 }],
			"@stylistic/member-delimiter-style": [
				"error",
				{
					multiline: { delimiter: "semi", requireLast: true },
					singleline: { delimiter: "semi", requireLast: false },
					multilineDetection: "brackets",
				},
			],
			"@stylistic/multiline-comment-style": ["error", "starred-block"],
			"@stylistic/multiline-ternary": ["error", "always-multiline"],
			"@stylistic/new-parens": ["error", "always"],
			"@stylistic/newline-per-chained-call": ["error", { ignoreChainWithDepth: 3 }],
			"@stylistic/no-confusing-arrow": ["error", { allowParens: true }],
			"@stylistic/no-extra-parens": [
				"off",
				"all",
				{
					conditionalAssign: false,
					returnAssign: false,
					nestedBinaryExpressions: false,
					ternaryOperandBinaryExpressions: false,
					enforceForSequenceExpressions: false,
					enforceForFunctionPrototypeMethods: false,
					nestedConditionalExpressions: false,
				},
			],
			"@stylistic/no-extra-semi": ["error"],
			"@stylistic/no-floating-decimal": ["error"],
			"@stylistic/no-mixed-operators": ["error"],
			"@stylistic/no-mixed-spaces-and-tabs": ["error"],
			"@stylistic/no-multi-spaces": ["error"],
			"@stylistic/no-multiple-empty-lines": ["error", { max: 3, maxEOF: 0, maxBOF: 0 }],
			"@stylistic/no-tabs": ["off"],
			"@stylistic/no-trailing-spaces": ["error"],
			"@stylistic/no-whitespace-before-property": ["error"],
			"@stylistic/nonblock-statement-body-position": ["error", "beside"],
			"@stylistic/object-curly-newline": ["error", { consistent: true }],
			"@stylistic/object-curly-spacing": ["error", "always"],
			"@stylistic/object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
			"@stylistic/one-var-declaration-per-line": ["error", "always"],
			"@stylistic/operator-linebreak": ["error", "before", { overrides: { "=": "after" } }],
			"@stylistic/padded-blocks": ["error", "never"],
			"@stylistic/padding-line-between-statements": ["off"],
			"@stylistic/quote-props": ["error", "as-needed"],
			"@stylistic/quotes": ["error", "double", { avoidEscape: true }],
			"@stylistic/rest-spread-spacing": ["error", "never"],
			"@stylistic/semi": ["error", "always"],
			"@stylistic/semi-spacing": ["error", { before: false, after: true }],
			"@stylistic/semi-style": ["error", "last"],
			"@stylistic/space-before-blocks": ["error", "always"],
			"@stylistic/space-before-function-paren": ["error", { anonymous: "never", named: "never", asyncArrow: "always", catch: "always" }],
			"@stylistic/space-in-parens": ["error", "never"],
			"@stylistic/space-infix-ops": ["error"],
			"@stylistic/space-unary-ops": ["error", { words: true, nonwords: false }],
			"@stylistic/spaced-comment": [
				"error",
				"always",
				{
					line: { exceptions: ["/"] },
					block: { exceptions: ["*"] },
				},
			],
			"@stylistic/switch-colon-spacing": ["error", { before: false, after: true }],
			"@stylistic/template-curly-spacing": ["error", "never"],
			"@stylistic/template-tag-spacing": ["error", "never"],
			"@stylistic/type-annotation-spacing": [
				"error",
				{
					before: true,
					after: true,
					overrides: {
						colon: { before: false, after: true },
					},
				},
			],
			"@stylistic/type-generic-spacing": ["error"],
			"@stylistic/type-named-tuple-spacing": ["error"],
			"@stylistic/wrap-iife": ["error", "inside"],
			"@stylistic/wrap-regex": ["error"],
			"@stylistic/yield-star-spacing": ["error", { before: false, after: true }],
		},
	},

	// Override default ignores of eslint-config-next.
	globalIgnores([
		// Default ignores of eslint-config-next:
		".next/**",
		"out/**",
		"build/**",
		"next-env.d.ts",
		"src/components/ui",
	]),
]);

export default eslintConfig;
